name: DevOps Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=devopsdb" >> .env
          echo "DB_USER=devopsuser" >> .env
          echo "DB_PASSWORD=devopspassword" >> .env

      - name: Build Docker containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Check health endpoint
        run: |
          sleep 20
          curl -f http://localhost:8080/health

      - name: Stop containers
        if: always()
        run: docker compose down

  deploy:
    needs: build-test
    if: github.event_name == 'push'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "DB_HOST=db" > .env
          echo "DB_NAME=devopsdb" >> .env
          echo "DB_USER=devopsuser" >> .env
          echo "DB_PASSWORD=devopspassword" >> .env

      - name: Deploy containers on Ubuntu server
        run: |
          docker compose down
          docker compose up -d --build